CLASS zbp_qm_ba_ilot_h DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zqm_ba_ilot_h.

  PUBLIC SECTION.
    CLASS-DATA gv_ins_lot TYPE c LENGTH 12.
    CLASS-DATA gt_ilot_h TYPE TABLE OF zqm_t_ilot_h.

ENDCLASS.



CLASS ZBP_QM_BA_ILOT_H IMPLEMENTATION.
ENDCLASS.
