****CLASS LHC_ZQM_BA_INPROCESSINSPECTION DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
****  PRIVATE SECTION.
****    METHODS:
****      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
****        IMPORTING
****           REQUEST requested_authorizations FOR Item
****        RESULT result.
****ENDCLASS.
****
****CLASS LHC_ZQM_BA_INPROCESSINSPECTION IMPLEMENTATION.
****  METHOD GET_GLOBAL_AUTHORIZATIONS.
****  ENDMETHOD.
****ENDCLASS.
